#!/usr/bin/env python3
import os
import sys
import re

if os.path.exists('.grip') is False:
        print('grip-show: error: grip repository directory .grip not found', file=sys.stderr)
        sys.exit(1)

if len(sys.argv) < 2:
        print('usage: grip-show <commit>:<filename>', file=sys.stderr)
        sys.exit(1)

match = re.search('[0-9]*:.*', sys.argv[1])

if match is None:
        print('usage: grip-show <commit>:<filename>', file=sys.stderr)
        sys.exit(1)

args = sys.argv[1].split(':')

if re.search('^[a-zA-Z0-9]+[a-zA-Z0-9._-]*$', args[1]) is None:
        print(f"grip-show: error: invalid filename '{args[1]}'", file=sys.stderr)
        sys.exit(1)

if args[0] != '':
        commit_num = args[0]
        commit_path = '.grip/commits/' + commit_num
        file_path = f'{commit_path}/{args[1]}'

        if os.path.exists(commit_path) is False:
                print(f"grip-show: error: unknown commit '{commit_num}'", file=sys.stderr)
                sys.exit(1)
        
        if os.path.exists(file_path) is False:
                print(f"grip-show: error: '{args[1]}' not found in commit {commit_num}", file=sys.stderr)
                sys.exit(1)

else:
        file_path = '.grip/INDEX/' + args[1]

        if os.path.exists(file_path) is False:
                print(f"grip-show: error: '{args[1]}' not found in index", file=sys.stderr)
                sys.exit(1)

with open(file_path, 'r') as file:
                for line in file:
                        print(line.strip())
        